number = []
number.insert(0,6)
number.insert(1,5)
number.insert(2,10)
print(number)
number.remove(6)
number.append(1)
number.append(9)
number.sort()
print(number)
number.pop(-1)
number.reverse()
print(number)